# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'completeddialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_completedDialog(object):
    def setupUi(self, completedDialog):
        completedDialog.setObjectName("completedDialog")
        completedDialog.resize(279, 104)
        completedDialog.setMinimumSize(QtCore.QSize(279, 104))
        completedDialog.setMaximumSize(QtCore.QSize(279, 104))
        self.completedOKButton = QtWidgets.QPushButton(completedDialog)
        self.completedOKButton.setGeometry(QtCore.QRect(110, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.completedOKButton.setFont(font)
        self.completedOKButton.setObjectName("completedOKButton")
        self.numworldsDisplay = QtWidgets.QLabel(completedDialog)
        self.numworldsDisplay.setGeometry(QtCore.QRect(40, 30, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numworldsDisplay.setFont(font)
        self.numworldsDisplay.setText("")
        self.numworldsDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.numworldsDisplay.setObjectName("numworldsDisplay")

        self.retranslateUi(completedDialog)
        QtCore.QMetaObject.connectSlotsByName(completedDialog)

    def retranslateUi(self, completedDialog):
        _translate = QtCore.QCoreApplication.translate
        completedDialog.setWindowTitle(_translate("completedDialog", "Sector Generated!"))
        self.completedOKButton.setText(_translate("completedDialog", "OK"))
